name: ci-pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.12'
  APP_DIR: backend

defaults:
  run:
    working-directory: backend

permissions:
  contents: read
  security-events: write

jobs:
  build-and-test:
    name: Build, Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: ${{ env.APP_DIR }}/requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run lint
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    

  dependency-security:
    name: Dependency Vulnerability Scan (SCA)
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: oneka-backend
          path: ${{ env.APP_DIR }}
          format: ALL
          out: reports
          args: --failOnCVSS 7 --enableRetired

      - name: Upload Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: dependency-check-report
          path: reports/

  container-security:
    name: Container Security Scan
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: ensure dockekrfile exists
        run: |
          if [ ! -f Dockerfile ]; then
            echo "Dockerfile not found!"
            exit 1
          fi
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Build Docker image with cache
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
        with:
          context: ./${{ env.APP_DIR }}
          file: ./${{ env.APP_DIR }}/Dockerfile
          tags: oneka-backend:ci
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          image-ref: oneka-backend:ci
          format: sarif
          severity: HIGH,CRITICAL
          exit-code: '1'
          output: trivy-results.sarif

      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif

  notify:
    name: Notify CI Result
    runs-on: ubuntu-latest
    needs:
      - build-and-test
      - dependency-security
      - container-security
    if: always()

    steps:
      - name: CI Summary
        run: |
          echo "Build: ${{ needs.build-and-test.result }}"
          echo "Dependency Scan: ${{ needs.dependency-security.result }}"
          echo "Container Scan: ${{ needs.container-security.result }}"
